HMS/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using HMS.Areas.Dashboard.ViewModel;
using HMS.Entities;
using HMS.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccomodationTypesController : Controller
    {

        AccomodationTypesService objAccomodationTypesService = new AccomodationTypesService();
        AccomodationType accomodationType = new AccomodationType();

        // GET: Dashboard/AccomodatioTypes
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Listing()
        {
            AccomodationTypeViewModel objAccomodationTypeViewModel = new AccomodationTypeViewModel();
            objAccomodationTypeViewModel.AccomodationTypes = objAccomodationTypesService.GetAllAccomodationType();

            return PartialView("_Listing", objAccomodationTypeViewModel);
        }

        [HttpGet]
        public ActionResult Action(int? Id)
        {
            AccomodationTypeActionViewModel objAccomodationTypeActionViewModel = new AccomodationTypeActionViewModel();

            if (Id.HasValue)  //we are tyring to edit
            {
                var data = objAccomodationTypesService.GeAccomodationTypeById(Id.Value);
                objAccomodationTypeActionViewModel.Id = data.Id;
                objAccomodationTypeActionViewModel.Name = data.Name;
                objAccomodationTypeActionViewModel.Description = data.Description;

            }

            return PartialView("_Action", objAccomodationTypeActionViewModel);
        }

        [HttpPost]
        public JsonResult Action(AccomodationTypeActionViewModel modal)
        {
            JsonResult Json = new JsonResult();
            var result = false;
            AccomodationTypesService objAccomodationTypesService = new AccomodationTypesService();

            if (modal.Id>0)  //we are tyring to edit
            {
                var data = objAccomodationTypesService.GeAccomodationTypeById(modal.Id);

            //    data.Id = modal.Id;

                data.Name = modal.Name;
                data.Description = modal.Description;

                result = objAccomodationTypesService.UpdateAccomodationType(data);

            }
            else
            {
                accomodationType.Name = modal.Name;
                accomodationType.Description = modal.Description;
                 result = objAccomodationTypesService.SaveAccomodationType(accomodationType);

            }
           

            if (result)
            {
                Json.Data = new { Success = true };
            }
            else
            {
                Json.Data = new { Success = false,Message ="Unable to save" };


            }

            return Json;
        }

        [HttpGet]
        public ActionResult Delete(int? Id)
        {
            AccomodationTypeActionViewModel objAccomodationTypeActionViewModel = new AccomodationTypeActionViewModel();

            if (Id.HasValue)  //we are tyring to edit
            {
                var data = objAccomodationTypesService.GeAccomodationTypeById(Id.Value);
                objAccomodationTypeActionViewModel.Id = data.Id;

            }

            return PartialView("_Delete", objAccomodationTypeActionViewModel);
        }


        [HttpPost]
        public JsonResult Delete(AccomodationTypeActionViewModel modal)
        {
            JsonResult Json = new JsonResult();
            var result = false;
            AccomodationTypesService objAccomodationTypesService = new AccomodationTypesService();

            
                var data = objAccomodationTypesService.GeAccomodationTypeById(modal.Id);

                //    data.Id = modal.Id;

                result = objAccomodationTypesService.DeleteAccomodationType(data);

          

            if (result)
            {
                Json.Data = new { Success = true };
            }
            else
            {
                Json.Data = new { Success = false, Message = "Unable to Delete" };


            }

            return Json;
        }
    }
}

HMS/Areas/Dashboard/Views/AccomodationTypes/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="container-fluid">



    <div class="row">
        <div class="col-lg-12">

            <h2>AccomodationType</h2>

        </div>


    </div>


    <hr />
    <div class="row mb-3">
        <div class="col-lg-12">
            <form>
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2" required>
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit">
                            <i class="fa fa-search mr-1" aria-hidden="true"></i>Search
                        </button>
                        <button class="btn btn-outline-secondary" type="button">
                            <i class="fa fa-repeat mr-1" aria-hidden="true"></i>Reset
                        </button>
                        <button data-href="@Url.Action("Action", "AccomodationTypes")" class="btn btn-outline-success databtn" type="button" data-toggle="modal" data-target="#actionmodal" data-whatever="">
                            <i class="fa fa-plus mr-1" aria-hidden="true"></i>
                            Create
                        </button>
                    </div>
                </div>
            </form>
        </div>


    </div>

    
    <div class="row mb-2">
        <div class="col-lg-12">

            @{Html.RenderAction("Listing");}
        </div>


    </div>

    <div class="modal fade" id="actionmodal" tabindex="-1" role="dialog" aria-labelledby="actionmodalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        </div>
    </div>

</div>
<script>
    $('.databtn').click(function () {

        $.ajax({

            url: $(this).attr('data-href'),
        })
            .done(function (response) {
                $('#actionmodal .modal-dialog').html(response);

            });
   
});
</script>

HMS/Areas/Dashboard/Views/AccomodationTypes/_Action.cshtml
@model HMS.Areas.Dashboard.ViewModel.AccomodationTypeActionViewModel


<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> 
        @if (Model.Id>0)
        {
            <span>  Edit AccomodationType</span>

                }
        else
        {
        <span>  Add AccomodationType</span>
            }
            </h5>


            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form id="actionform">
            <input type="hidden" name="Id" value="@Model.Id"/>
            <div class="form-group">
                <label for="Name" class="col-form-label">Name:</label>
                <input type="text" class="form-control" placeholder="Enter name" name="Name" id="Name" value="@Model.Name" >
            </div>
            <div class="form-group">                

                <label for="Description" class="col-form-label">Description:</label>
                <textarea class="form-control" name="Description" placeholder="Enter Description">@Model.Description</textarea>
            </div>
        </form>
        <div class="errordiv">


        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="btnSave" type="button" class="btn btn-primary">Save</button>
    </div>
</div>
<script>   
    $('#btnSave').click(function () {

        $.ajax({

            url: '@Url.Action("Action", "AccomodationTypes")', 
            type:"post",
            data: $('#actionform').serialize(),
            
        })
      //  location.reload();
             //reload page after clicking save button

        .done(function (response) {
                if (response.Success)
                {
                    location.reload();

                }
                else {
                    $('.errordiv').html(response.Message);
                }
            });

});
</script>

HMS/Areas/Dashboard/Views/AccomodationTypes/_Delete.cshtml
@model HMS.Areas.Dashboard.ViewModel.AccomodationTypeActionViewModel


<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          
            <span>  Delete Accomodation Type</span>

           
        </h5>


        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form id="actionform">
            <input type="hidden" name="Id" value="@Model.Id" />
            <div class="alert-danger modal-header font-weight-bold">
                Do You Really want to delete?
            </div>
        </form>
        <div class="errordiv">


        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <i class="fa fa-times mr-1" aria-hidden="true"></i>
            Close
        </button>
        <button id="btnSave" type="button" class="btn btn-danger"> <i class="fa fa-trash-o mr-1" aria-hidden="true"></i>Delete</button>
    </div>
</div>
<script>

    $('#btnSave').click(function () {

        $.ajax({

            url: '@Url.Action("Delete", "AccomodationTypes")',
            type:"post",
            data: $('#actionform').serialize(),

        })
      //  location.reload();
             //reload page after clicking save button

        .done(function (response) {
                if (response.Success)
                {
                    location.reload();

                }
                else {
                    $('.errordiv').html(response.Message);
                }
            });

});
</script>

HMS/Areas/Dashboard/Views/AccomodationTypes/_Listing.cshtml
@model HMS.Areas.Dashboard.ViewModel.AccomodationTypeViewModel


@if(Model !=null && Model.AccomodationTypes!=null && Model.AccomodationTypes.Count()>0)
{ 
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col" width="20%">Name</th>
                <th scope="col" width="50%">Description</th>
                <th scope="col" width="20%">Action</th>
            </tr>
        </thead>
        <tbody>
            
         
                @foreach (var item in Model.AccomodationTypes)
                {
            <tr>

                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>
                    <button type="button"data-toggle="modal" data-target="#actionmodal" data-href="@Url.Action("Action", "AccomodationTypes",new {Id=item.Id})" class=" btn btn-primary databtn " style="width:100px">
                        <i class="fa fa-pencil mr-1" aria-hidden="true"></i>Edit

                    </button>
                    <button type="button" class=" btn btn-danger databtn" data-toggle="modal" data-target="#actionmodal" data-href="@Url.Action("Delete", "AccomodationTypes",new {Id=item.Id})"  style="width:100px">
                        <i class="fa fa-trash-o mr-1" aria-hidden="true"></i>Delete

                    </button>

                </td>
            </tr>
                }

           

        </tbody>
    </table>
}
else { 
<div class="alert alert-warning" role="alert" >
    Sorry! No result found

</div>

}